[phases.setup]
nixPkgs = ["openjdk"]

[phases.build]
cmds = [
    "chmod +x gradlew",
    "./gradlew clean shadowJar",
    "echo LS",
    "ls -l build/libs/"
]

[phases.start]
cmd = "java -jar build/libs/ktor-websocket-server-0.0.1-all.jar"
