ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
    engine:
        connectionGroupSize: 2   # número de hilos para aceptar conexiones
        workerGroupSize: 16      # hilos para manejar IO (Netty)
        callGroupSize: 32        # hilos para manejar tus corutinas
        requestQueueLimit: 8192  # cola de solicitudes pendientes
        responseWriteTimeoutSeconds: 60