ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
    engine:
        connectionGroupSize: 4    # número de hilos para aceptar conexiones
        workerGroupSize: 64       # hilos para manejar IO (Netty)
        callGroupSize: 128        # hilos para manejar tus corutinas
        requestQueueLimit: 100000 # cola de solicitudes pendientes
        responseWriteTimeoutSeconds: 60